<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>GitIt.Desktop</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GitIt.Core\GitIt.Core.csproj" />
    <ProjectReference Include="..\GitIt.UserAnnotations\GitIt.UserAnnotations.csproj" />
  </ItemGroup>
</Project>
